blank_issues_enabled: false

contact_links:
  - name: Questions and community creations
    url: https://github.com/cirruslabs/cirrus-ci-docs/discussions
    about: Please use discussions if you have a question (not a bug or feature report), or something to share with the community.
